---
  tasks:
    - name: 'loading'
      import: 'tasks.loading.loading'
      classname: 'LoadingTask'
      storage: 'storage'
    - name: 'preprocessing'
      import: 'tasks.preprocessing.preprocessing'
      classname: 'PreprocessingTask'
      storage: 'storage'

  flows:
    - 'flow'

  storages:
    - name: 'storage'
      classname: 'InMemoryStorage'
      import: 'selinon.storages.memory'
      configuration:
        echo: false
